### ISSUE TITLE
Práctica de Calidad-Prestadores de Servicio

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/practica-de-calidad_Prestadores-de-Servicio#1]
[PRÁCTICA_DE_CALIDAD.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-calidad_Prestadores-de-Servicio/files/7342587/PRACTICA_DE_CALIDAD.pdf)

**Comment by Edwin-1012** [comment]
Calificación: 20%
Contiene los puntos requeridos de igual manera muestra las partes requeridas.

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
